name: ml-notebooks
channels:
  - defaults
  - conda-forge
dependencies:
  - black
  - kaggle
  - keras=2.10.0
  - numpy=1.21.5
  - pandas=1.4.2
  - python=3.9.7
  - scikit-learn=0.24.1
  - scipy=1.7.3
  - setuptools=65.5.*
  - tensorflow=2.10.0
